const brands = [
  `Nike`,
  `nike`,
  `adidas`,
  `Adidas`,
  `Air Jordan`,
  `air jordan`,
  `Jordan`,
  `jordan`,
  `Yeezy`,
  `yeezy`,
  `New Balance`,
  `new balance`,
  `Saucony`,
  `saucony`,
  `Under Armour`,
  `under armour`,
  `Puma`,
  `puma`,
  `Timberland`,
  `timberland`,
  `Uggs`,
  `uggs`,
  `clarks`,
  `Clarks`,
  `Fila`,
  `fila`,
  `Converse`,
  `converse`,
  `Asics`,
  `asics`,
  `Reebok`,
  `reebok`,
];

const squareSpaceHeaders = [
  `Product URL`,
  `Title`,
  `Description`,
  `Product Type`,
  `Tags`,
  `Categories`,
  `Visible`,
  `Hosted Image URLs`,
  `SKU`,
  `Option Name 1`,
  `Option Value 1`,
  `Option Name 2`,
  `Option Value 2`,
  `Option Name 3`,
  `Option Value 3`,
  `Price`,
  `Sale Price`,
  `On Sale`,
  `Weight`,
  `Length`,
  `Width`,
  `Height`,
  `Stock`,
];

module.exports = { brands, squareSpaceHeaders };


/*
const correctHeaderDataExample = [
  [
    `Nike-React-Element-87-Undercover-Volt`,
    `Nike React Element 87 Undercover Volt`,
    `What's better than the classic 90s' TV series "New York Undercover"? Nothing really, but the Nike React Element 87 Undercover Volt is close. First unveiled by Jun Takahasi at UNDERCOVER's Paris Fashion Week's FW18 show in March, these shoes feature 'UNDERCOVER by Jun Takahasi' stamped on the translucent yellow uppers, the cork footbed has been replaced with a mesh one, and the colors coordinate with the shoes' uppers. If you love Malik Yoba, Dick Wolf, UNDERCOVER, and Nike, then these jawns are for you.`,
    `Physical`,
    `Nike, React, Element, 87, Undercover, Volt`,
    `men`,
    `TRUE`,
    `https://stockx.imgix.net/Nike-React-Element-87-Undercover-Volt-Product.jpg`,
    `,`,
    `,`,
    `,`,
    `,`,
    `,`,
    `,`,
    `,`,
    `230.00`,
    `,`,
    `,`,
    `,`,
    `,`,
    `,`,
    `,`,
    `1`,
  ],
];
*/
